function subjects = getDTISubjects()

% returns cell array of subject ids to include in dti Shock & Awe analyses

%%%%%%%%%%%%%%%%%
    
  subjects = {
      'sa01',...
        'sa07',...
        'sa10',...
        'sa11',...
        'sa13',...
        'sa14',...
        'sa16',...
        'sa18',...
        'sa19',...
        'sa20',...
        'sa21',...
        'sa22',...
        'sa23',...
        'sa24',...
        'sa25',...
        'sa26',...
        'sa27',...
        'sa28',...
        'sa29',...
        'sa30',...
        'sa31',...
        'sa32',...
        'sa33',...
        'sa34'};  
    
   

   